# Solid Queue Recurring Tasks Configuration
# These jobs run on a schedule to send notifications

# Daily digest - sends consolidated email summary
send_daily_digest:
  class: SendDailyDigestJob
  schedule: "0 9 * * *"  # Every day at 9:00 AM
  queue: default

# Due date checker - warns about upcoming deadlines
check_upcoming_due_dates:
  class: CheckUpcomingDueDatesJob
  schedule: "0 8 * * *"  # Every day at 8:00 AM
  queue: default
